---
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  schedule:
    - cron: "0 14 * * 1" # Every Monday at 9 A.M. CST.
  workflow_dispatch:

env:
  CI: true
  GODOT_VERSION: "4.2.1"
  GDTOOLKIT_VERSION: "4.2.2"
  DENO_VERSION: "v1.40.3"

permissions:
  contents: read

jobs:
  build:
    name: Build
    needs: []
    timeout-minutes: ${{ (matrix.target == 'web') && 5 || 10 }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - web
          # - macos
        include:
          - target: web
            os: ubuntu-latest
            godot-flags: --export-release "Web" build/index.html
          # - target: macos
          #   os: macos-latest
          #   godot-flags: --export-release "OS X"

    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: 🤖 Set up Godot
        uses: chickensoft-games/setup-godot@d3fbddfbafb76fbce64d878aa3d31090e5d0fe0c # v1.5.6
        with:
          version: ${{ env.GODOT_VERSION }}
          use-dotnet: false
      - name: 🔬 Verify setup
        run: godot --version
      - name: 🔌 Make and delete directories
        run: mkdir build/ && rm -rf addons/{godot-git-plugin,wakatime}
      - name: 🔧 Build
        run: godot --headless ${{ matrix.godot-flags }}
      - name: ⚙️ Upload build
        if: matrix.target == 'web'
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: build-${{ matrix.target }}
          path: "./build"
          if-no-files-found: error

  lint:
    name: Linting
    needs: []
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: 🤖 Set up Godot
        uses: Scony/godot-gdscript-toolkit@4dcf42a0efea21940e8514d66a39a37e599c39ba # master
        with:
          version: ${{ env.GDTOOLKIT_VERSION }}
      - name: 🔬 Verify setup
        run: gdparse --version
      - name: 🕵️ Analyze project source
        run: gdlint .

  format:
    name: Formatting
    needs: []
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: 🤖 Set up Godot
        uses: Scony/godot-gdscript-toolkit@4dcf42a0efea21940e8514d66a39a37e599c39ba # master
        with:
          version: ${{ env.GDTOOLKIT_VERSION }}
      - name: 🔬 Verify setup
        run: gdparse --version
      - name: ✨ Verify formatting
        run: gdformat --check $(find . -name '*.gd' -not -path "./addons/*")

  check:
    name: Check TS
    needs: []
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      pull-requests: write # Needed for Biome PR comments.

    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: 🦕 Install Deno
        uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba # v1.1.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: 🕵️ Run linter, verify formatting, typecheck
        run: deno task ci
      - name: 🧪 Run tests
        run: deno task test
      - name: 📊 Collect coverage
        run: deno task test:coverage

  deploy:
    name: Deploy to Deno Deploy
    needs: [build, check]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      id-token: write # Needed to authenticate with Deno Deploy.
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: ⚙️ Download build
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: build-web
          path: "./build"
      - name: 🔧 Deploy
        uses: denoland/deployctl@1e1637600646cbc6826a4bacd359713fc24d25b3 # 1.11.0
        with:
          project: "wizards-in-calculus"
          entrypoint: server/server.ts
          include: |
            server
            build
            deno.json
            deno.lock
